"""empty message

Revision ID: d8405e9a405a
Revises: d1d95bd938ce
Create Date: 2021-07-01 15:21:26.685587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8405e9a405a'
down_revision = 'd1d95bd938ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'name')
    op.add_column('pages', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pages', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'book_id')
    op.add_column('books', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
